variables:
  APP_NAME: "th2-message-store"
  MAJOR_VERSION: "1"
  MINOR_VERSION: "5"
  MAINTENANCE_VERSION: '0'

include:
  - project: 'vivarium/th2/pipelines'
    ref: master
    file: '/.gitlab-ci-java.yml'
