name: Build and publish Docker image to Github Container Registry ghcr.io

on:
  push:
    branches-ignore:
      - master
      - version-*
      - dependabot**
    paths-ignore:
      - README.md

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
    with:
      build-target: 'Docker'
      pico-test-enabled: true
      docker-username: ${{ github.actor }}
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}
      nvd-api-key: ${{ secrets.NVD_APIKEY }}
  pico-test:
    uses: peter-evans/repository-dispatch@v3
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      repository: th2-net/th2-pico-test
      event-type: run-pico-test-workflow
      client-payload: '{"component-image": "${{ github.repository }}", "component-image-version": "5.9.0-dev"}'