name: Scan licenses and vulnerabilities in java project

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    # FIXME: migrate to main branch after https://github.com/th2-net/.github/pull/100 merge
    uses: th2-net/.github/.github/workflows/compound-java-scan.yml@java-scan-workflow
    secrets:
      nvd-api-key: ${{ secrets.NVD_APIKEY }}